apps/web/src/app/page.tsx, apps/web/src/components/Footer.tsx, apps/web/src/components/home/LatestComments.tsx, apps/web/src/components/home/Testimonials.tsx, apps/web/tailwind.config.ts, package.json, pnpm-lock.yaml
=> feat: add testimonials

apps/api/src/config/database.config.ts, apps/api/src/datasource.ts, apps/api/src/entities/token.entity.ts, apps/api/src/entities/twitter-username-history.entity.ts, apps/api/src/tokens/tokens.controller.ts, apps/api/src/tokens/tokens.module.ts, apps/api/src/tokens/tokens.service.ts, apps/api/src/tokens/twitter-history.service.ts, apps/web/src/app/links/page.tsx, apps/web/src/app/tokens/[mintAddress]/page.tsx, apps/web/src/components/Footer.tsx, apps/web/src/components/layout/Header.tsx, apps/web/src/components/tokens/TokenStats.tsx, apps/web/src/lib/api.ts, apps/web/src/types/token.ts, packages/types/src/token.ts
=> feat(twitter): get username history of a Twitter account

.github/workflows/deploy.yml, .github/workflows/issue-to-discord.yml
This is part of #55 PR to split and make it easy to digest
=> feat: improve build time CI/CD + add open issue in discord

apps/web/src/app/layout.tsx, apps/web/src/components/layout/Header.tsx, apps/web/src/components/ui/rich-text-editor.tsx
- fix favicon in layout
- fix image ratio in header
- fixed tiptap hydration
- fix hydration mismatches
=> Fix browser errors

apps/web/src/app/users/[username]/opengraph-image.tsx, apps/web/src/app/users/[username]/page.tsx
=> feat(profile): share beautiful dynamic image on shared profiles

apps/api/src/app.module.ts, apps/api/src/auth/decorators/current-user.decorator.ts, apps/api/src/auth/decorators/index.ts, apps/api/src/auth/guards/index.ts, apps/api/src/auth/guards/optional-auth.guard.ts, apps/api/src/auth/index.ts, apps/api/src/config/database.config.ts, apps/api/src/entities/token-watchlist.entity.ts, apps/api/src/entities/token.entity.ts, apps/api/src/entities/user.entity.ts, apps/api/src/migrations/1717300000000-CreateTokenWatchlistsTable.ts, apps/api/src/tokens/tokens.controller.ts, apps/api/src/tokens/tokens.module.ts, apps/api/src/tokens/tokens.service.ts, apps/api/src/watchlist/watchlist.controller.ts, apps/api/src/watchlist/watchlist.module.ts, apps/api/src/watchlist/watchlist.service.ts, apps/web/src/app/tokens/[mintAddress]/page.tsx, apps/web/src/app/watchlist/page.tsx, apps/web/src/components/auth/UserMenu.tsx, apps/web/src/components/tokens/WatchlistButton.tsx, apps/web/src/components/ui/tabs.tsx, apps/web/src/lib/api.ts, package.json, pnpm-lock.yaml
=> feat(watchlist): add token watchlist

apps/api/src/app.module.ts, apps/api/src/datasource.ts, apps/api/src/entities/index.ts, apps/api/src/entities/token-sentiment.entity.ts, apps/api/src/entities/token.entity.ts, apps/api/src/entities/user.entity.ts, apps/api/src/migrations/1717600000000-AddTokenSentiments.ts, apps/api/src/tokens/dto/update-sentiment.dto.ts, apps/api/src/tokens/token-sentiment.controller.ts, apps/api/src/tokens/token-sentiment.service.ts, apps/api/src/tokens/tokens.module.ts, apps/web/src/app/tokens/[mintAddress]/page.tsx, apps/web/src/lib/api.ts, packages/types/src/token.ts
=> feat(token): add community sentiment

.github/workflows/docker-build.yml, apps/api/Dockerfile, apps/web/Dockerfile
=> Build machine in GitHub

.github/workflows/docker-build.yml
=> fix: action docker build

apps/api/src/token-calls/token-calls.service.ts, apps/api/src/tokens/tokens.controller.ts, apps/api/src/tokens/tokens.service.ts, apps/web/src/app/admin/streaks/page.tsx, apps/web/src/app/token-calls/[callId]/opengraph-image.tsx, apps/web/src/app/token-calls/[callId]/page.tsx, apps/web/src/app/token-calls/page.tsx, apps/web/src/app/tokens/[mintAddress]/page.tsx, apps/web/src/components/token-calls/token-page/DisplayUserCall.tsx, apps/web/src/components/token-calls/token-page/MakeCallForm.tsx, apps/web/src/components/token-calls/token-page/MakeCallModal.tsx, apps/web/src/components/token-calls/token-page/TokenCallsSection.tsx, apps/web/src/components/tokens/TokenStats.tsx, apps/web/src/lib/api.ts, apps/web/src/lib/utils.ts, packages/types/src/token.ts
=> feat(token call): check price prediction on submit and in backend

apps/api/src/comments/comments.service.ts, apps/api/src/comments/dto/comment-response.dto.ts, apps/api/src/entities/comment.entity.ts, apps/api/src/entities/token-call.entity.ts, apps/api/src/migrations/1745082957461-AddCommentTypeAndTokenCallRelation.ts, apps/api/src/scripts/seed-database.ts, apps/api/src/token-calls/dto/create-token-call.dto.ts, apps/api/src/token-calls/dto/token-call-response.dto.ts, apps/api/src/token-calls/token-calls.controller.ts, apps/api/src/token-calls/token-calls.module.ts, apps/api/src/token-calls/token-calls.service.ts, apps/web/src/app/tokens/[mintAddress]/page.tsx, apps/web/src/components/comments/CommentSection.tsx, apps/web/src/components/token-calls/token-page/MakeCallForm.tsx, apps/web/src/components/token-calls/token-page/MakeCallModal.tsx, apps/web/src/components/token-calls/token-page/TokenCallsSection.tsx, apps/web/src/lib/api.ts, apps/web/src/lib/utils.ts, packages/types/src/comment.ts, packages/types/src/token-call.ts
=> Add mandatory explanation for prediction that goes in comments

apps/api/src/token-calls-leaderboard/dto/tokenCallsLeaderboard-entry.dto.ts, apps/api/src/token-calls-leaderboard/tokenCallsLeaderboard.service.ts, apps/web/src/app/leaderboard/page.tsx, apps/web/src/components/homepage/TopReputationUsers.tsx
**🏆 Token Call Leaderboard Ranking Method**
The leaderboard now uses a fair, activity-weighted scoring system to rank users based on both their accuracy and consistency in making token calls.
**How it works:**
Adjusted Score Formula:
**Each user's score is calculated as:**
`Adjusted Score = (Successful Calls / Total Calls) * ln(Total Calls + 1)`
**Success Rate:** Measures the percentage of correct calls.
**Total Calls:** Rewards users who contribute more, but with diminishing returns (using the natural logarithm).
**No Minimum Calls:** All users with at least one call are ranked.
**Tie-breaker:**
If two users have the same Adjusted Score, the user with the higher average multiplier (average gain on successful calls) is ranked higher.
**Leaderboard Columns:**
Hit Rate: Percentage of …
=> feat(leaderboard): fix ranking for token calls

apps/api/src/tokens/tokens.controller.ts, apps/api/src/tokens/tokens.service.ts, apps/web/src/app/tokens/[mintAddress]/page.tsx, apps/web/src/components/tokens/bundles/BundleSummaryCard.tsx, apps/web/src/components/tokens/bundles/BundleTable.tsx, apps/web/src/components/tokens/bundles/TokenBundlesSection.tsx, apps/web/src/components/ui/dialog.tsx, apps/web/src/lib/api.ts, packages/types/src/token.ts
=> Add token bundles

apps/api/src/tipping/dto/tip-pagination-query.dto.ts, apps/api/src/tipping/tipping.controller.ts, apps/api/src/tipping/tipping.module.ts, apps/api/src/tipping/tipping.service.ts, apps/web/src/app/account/layout.tsx, apps/web/src/app/account/tips/page.tsx, apps/web/src/components/account/TipsTable.tsx, apps/web/src/components/comments/CommentSection.tsx, apps/web/src/lib/api.ts, apps/web/src/lib/utils.ts, packages/types/src/tip.ts
=> feat(tips): add tips menu in account and display history of tips

apps/web/package.json, apps/web/src/app/tokens/[mintAddress]/page.tsx, apps/web/src/components/token/EmbedButtonDialog.tsx, apps/web/src/components/ui/checkbox.tsx, pnpm-lock.yaml
=> Embed button generator on token page

apps/web/src/app/tokens/[mintAddress]/page.tsx, apps/web/src/components/tokens/TokenStats.tsx, apps/web/src/components/tokens/TwitterHistoryTooltip.tsx, apps/web/src/components/tokens/WebsiteInfoTooltip.tsx, apps/web/src/components/ui/tooltip.tsx
=> Domain age (creation/expiration date)

apps/api/src/users/dto/user-activity.dto.ts, apps/api/src/users/users.controller.ts, apps/api/src/users/users.service.ts, apps/web/src/app/users/[username]/Activity.tsx, apps/web/src/lib/api.ts, packages/types/src/user.ts, pnpm-lock.yaml
=> feat(profile): add searchbar in activities section

apps/web/src/app/tokens/[mintAddress]/opengraph-image.tsx
=> Add opengraph image when sharing token

apps/api/src/auth/auth.controller.ts, apps/api/src/auth/dto/user-response.dto.ts, apps/api/src/entities/user.entity.ts, apps/api/src/migrations/1746794736970-AddUserBio.ts, apps/api/src/tokens/tokens.service.ts, apps/api/src/users/dto/update-profile.dto.ts, apps/api/src/users/users.controller.ts, apps/api/src/users/users.service.ts, apps/web/src/app/account/layout.tsx, apps/web/src/app/account/profile/page.tsx, apps/web/src/app/users/[username]/components/UserProfileHeaderClient.tsx, apps/web/src/components/auth/UserMenu.tsx, apps/web/src/lib/api.ts, packages/types/src/user.ts
=> Change user bio + name

apps/api/src/comments/comments.service.ts, apps/api/src/comments/dto/comment-response.dto.ts, apps/api/src/comments/dto/create-comment.dto.ts, apps/api/src/entities/comment.entity.ts, apps/api/src/gamification/services/badge-scheduler.service.ts, apps/api/src/migrations/1747159064160-AddMcapToComments.ts, apps/web/src/components/comments/CommentSection.tsx, apps/web/src/types/comment.ts, packages/types/src/comment.ts
=> Add market cap at time of comment creation

apps/api/src/credits/credits.controller.ts, apps/api/src/credits/credits.module.ts, apps/api/src/credits/credits.service.ts, apps/web/src/app/account/credits/page.tsx, apps/web/src/lib/api.ts, packages/types/src/credits.ts
=> Add credit bonuses for holders

apps/api/package.json, apps/api/src/entities/token-call.entity.ts, apps/api/src/migrations/1747411069034-AddContestEntryToTokenCall.ts, apps/api/src/token-calls/dto/create-token-call.dto.ts, apps/api/src/token-calls/token-calls.service.ts, apps/web/src/app/faq/page.tsx, apps/web/src/components/layout/ContestBanner.tsx, apps/web/src/components/layout/Header.tsx, apps/web/src/components/token-calls/token-page/MakeCallForm.tsx, packages/types/src/token-call.ts, pnpm-lock.yaml
=> Contest setup

apps/api/.env.example, apps/api/src/tokens/tokens.controller.ts, apps/api/src/tokens/tokens.service.ts, apps/web/src/app/tokens/[mintAddress]/page.tsx, apps/web/src/components/tokens/HolderHistoryChart.tsx, apps/web/src/components/tokens/TokenStats.tsx, apps/web/src/lib/api.ts, packages/types/src/token.ts
=> Add holder chart in the token information section

.cursor/rules/code-structure.mdc, apps/api/src/tokens/tokens.controller.ts, apps/api/src/tokens/tokens.service.ts, apps/api/src/twitter-automation/twitter-automation.service.ts, apps/web/src/app/tokens/[mintAddress]/page.tsx, apps/web/src/lib/api.ts, packages/types/src/token.ts
=> Added risk score on every token

apps/api/.env.example, apps/api/src/tokens/tokens.controller.ts, apps/api/src/tokens/tokens.module.ts, apps/api/src/tokens/tokens.service.ts, apps/api/src/tokens/twitter-feed.service.ts, apps/api/src/tokens/twitter-history.service.ts, apps/web/src/components/tokens/token-page/TokenPageTabs.tsx, apps/web/src/components/tokens/token-page/tabs/TokenTwitterTab.tsx, apps/web/src/components/tokens/token-page/tabs/TwitterFeedLoader.tsx, apps/web/src/lib/api.ts, packages/types/src/token.ts
=> Add twitter feed on each token

apps/api/src/auth/dto/user-response.dto.ts, apps/api/src/tokens/tokens.module.ts, apps/api/src/users/users.controller.ts, apps/api/src/users/users.module.ts, apps/api/src/users/users.service.ts, apps/web/src/app/users/[username]/components/UserProfileHeaderClient.tsx, apps/web/src/components/tokens/TwitterInfoTooltip.tsx, apps/web/src/components/tokens/token-page/TokenPageHeader.tsx, apps/web/src/lib/api.ts
=> Add twitter preview on profile
